application: polymer-project-dashboard
version: 1
runtime: python27
api_version: 1
threadsafe: no

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: "latest"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /bower_components
  static_dir: bower_components

- url: /elements
  static_dir: elements

- url: /remoteapi.*
  script: google.appengine.ext.remote_api.handler.application
  login: admin

- url: .*
  script: application.app